export const CREATE_ATTRIBUTE = 'CREATE_ATTRIBUTE';
export const EDIT = 'EDIT';
export const DELETE = 'DELETE';

export const OPEN_ERROR = 'OPEN_ERROR';
export const CLOSE_ERROR = 'CLOSE_ERROR';

export const OPEN_CREATING_DIALOG = 'OPEN_CREATING_DIALOG';
export const OPEN_EDITING_DIALOG = 'OPEN_EDITING_DIALOG';
export const CLOSE_CREATING_DIALOG = 'CLOSE_CREATING_DIALOG';

export const OPEN_DELETING_DIALOG = 'OPEN_DELETING_DIALOG';
export const CLOSE_DELETING_DIALOG = 'CLOSE_DELETING_DIALOG';


